monitoringSettings:
  pollingFrequencyCronExpression: 0,15,30,45 * * * * *
  timeOutForPollRequestSeconds: 5

webpages:
  -
    url: http://start.spring.io/
    mandatoryContent: "Secure your application"
  -
    url: https://facebook.github.io/react/
    mandatoryContent: "painless"
  -
    url: https://angular.io/
    mandatoryContent: "One framework."
  -
    url: https://www.oracle.com/
    mandatoryContent: "unmatched content by charandeep test."
  -
    url: https://somerandomnotavailablesite.com/
    mandatoryContent: "content does not matter here"
